/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
 
import java.util.ArrayList;
import java.util.List;

import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import classes.Categoria;
import classes.Livros;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import java.awt.Font;
import javax.swing.JLabel;
import java.awt.Dimension;
import javax.swing.JButton;


public class FormLivros extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormLivros
     */
    List<Livros> listaDeLivros;
	private AbstractButton tableClasses;
    
    public FormLivros() {
        initComponents();
        
        listaDeLivros = new ArrayList<Livros>();
        
        carregarTabela();
        carregarCategorias();
    }
    
    public void carregarCategorias(){
        Categoria c0 = new Categoria(0,"Selecione...");
        Categoria c1 = new Categoria(1,"Ficcao Científica");
        Categoria c2 = new Categoria(2,"Didatico");
        Categoria c3 = new Categoria(3,"Literatura");
        Categoria c4 = new Categoria(4,"Folclore");
        
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement( c0 );
        model.addElement( c1 );
        model.addElement( c2 );
        model.addElement( c3 );
        model.addElement( c4 );
        
        cmbCategoria.setModel( model );
        
    }
    
    private void carregarTabela(){
        String[] colunas = {"Titulo" , "Autor", "Categoria"};
        
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers( colunas );
        
        
        for(Livros livro : listaDeLivros){
            Object[] linha = { livro.titulo , livro.autor, livro.categoria.nome };
            tableModel.addRow( linha );
        }
        
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Arial", Font.PLAIN, 12));
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Arial", Font.PLAIN, 12));
        cmbCategoria = new javax.swing.JComboBox<>();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLivros = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Livros");
        setPreferredSize(new Dimension(600, 600));

        jLabel1.setText("Titulo:");

        jLabel2.setText("Categoria:");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Alimentos", "Bebidas", "Eletrônicos" }));

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Folclore", "O que e Folclore", "Carlos Rodrigues Brandao"},
                {"Ficção Científica", "Slam", "Nick Hornby", },
                {"Didático", "Informática Internet e Aplicativos", "Cicero caicara Junior"},
                {"Literatura", "Contos", "Machado de Assis"},
                {"Literatura", "O Cortiço", "Aluisio Azevedo"}
            },
            new String [] {
                "Categoria", "Titulo", "Autor"
            }
        ));
        jScrollPane1.setViewportView(tableLivros);
        
        textField = new JTextField();
        textField.setColumns(10);
        
        JLabel lblNewLabel = new JLabel("Autor:");
        lblNewLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        
        JButton btnNewButton = new JButton("Salvar");
        btnNewButton.setFont(new Font("Arial", Font.BOLD, 12));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(22)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 542, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblNewLabel)
        							.addGap(18)
        							.addComponent(textField, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel2)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(cmbCategoria, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)))
        					.addGap(486)
        					.addComponent(btnSalvar))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel1)
        					.addGap(18)
        					.addComponent(txtNome, GroupLayout.PREFERRED_SIZE, 504, GroupLayout.PREFERRED_SIZE))))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(252)
        			.addComponent(btnNewButton))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(23)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(btnSalvar)
        					.addGap(25))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblNewLabel))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel2)
        						.addComponent(cmbCategoria, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        			.addGap(30)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 323, GroupLayout.PREFERRED_SIZE)
        			.addGap(31)
        			.addComponent(btnNewButton)
        			.addGap(35))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
        String nome = txtNome.getText();
        if( nome.isEmpty() || cmbCategoria.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "O nome e a categoria são obrigatórios!");
        }else{
            Livros livro =  new Livros();
            livro.titulo = nome;
            livro.autor = "autor";
                    
            livro.categoria = (Categoria)  cmbCategoria.getSelectedItem();
            
            
            
            carregarTabela();
            
            txtNome.setText("");
            cmbCategoria.setSelectedIndex( 0 );
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLivros;
    private javax.swing.JTextField txtNome;
    private JTextField textField;
}
