package telas;

import java.text.ParseException;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JTextField;
import javax.swing.LayoutStyle.ComponentPlacement;

import classes.Aluno;
import classes.Cliente;
import classes.Professor;
import javax.swing.JLabel;
import java.awt.Font;
import javax.swing.JTextArea;
import java.awt.Dimension;


public class FormClientes extends javax.swing.JInternalFrame {

    public FormClientes() {
    	setMaximizable(true);
    	setResizable(true);
    	setClosable(true);
        try {
			initComponents();
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws java.text.ParseException {

        buttonGroupTipoCliente = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        rbPRF = new javax.swing.JRadioButton();
        rbAluno = new javax.swing.JRadioButton();
        lblCPF = new javax.swing.JLabel();
        lblCPF.setFont(new Font("Arial", Font.PLAIN, 12));
        txtCPF = new javax.swing.JFormattedTextField();
        lblMatricula = new javax.swing.JLabel();
        lblMatricula.setFont(new Font("Arial", Font.PLAIN, 12));
        btnSalvar = new javax.swing.JButton();
        setIconifiable(true);
        setTitle("Formulário de Cliente");
        setPreferredSize(new Dimension(700, 600));

        jLabel1.setText("Nome: ");

        jLabel2.setText("Telefone:");

        buttonGroupTipoCliente.add(rbPRF);
        rbPRF.setText("Professor");
        rbPRF.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPFItemStateChanged(evt);
            }
        });

        buttonGroupTipoCliente.add(rbAluno);
        rbAluno.setText("Aluno");
        rbAluno.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbPJItemStateChanged(evt);
            }
        });
        rbAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPJActionPerformed(evt);
            }
        });

        lblCPF.setText("CPF:");
        lblCPF.setEnabled(false);

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.setEnabled(false);

        lblMatricula.setText("Matricula:");
        lblMatricula.setEnabled(false);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        
        txtMatricula = new JTextField();
        
        JLabel lblNewLabel = new JLabel("Endereco:");
        lblNewLabel.setFont(new Font("Arial", Font.PLAIN, 12));
        
        txtEndereco = new JTextField();
        txtEndereco.setColumns(10);
        
        JLabel lblNewLabel_1 = new JLabel("E-mail:");
        lblNewLabel_1.setFont(new Font("Arial", Font.PLAIN, 12));
        
        txtEmail = new JTextField();
        txtEmail.setColumns(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(19)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(lblNewLabel)
        						.addComponent(lblNewLabel_1))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtEmail, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        						.addComponent(txtEndereco, GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel2)
        						.addComponent(jLabel1))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(txtNome, GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        						.addComponent(txtTelefone, GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))))
        			.addGap(67))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(28)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(rbPRF)
        				.addComponent(rbAluno)
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblMatricula)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(txtMatricula, GroupLayout.PREFERRED_SIZE, 337, GroupLayout.PREFERRED_SIZE))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(lblCPF, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(txtCPF, GroupLayout.PREFERRED_SIZE, 255, GroupLayout.PREFERRED_SIZE)))))
        			.addContainerGap(257, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(257)
        			.addComponent(btnSalvar)
        			.addContainerGap(364, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(42)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtNome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(25)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel2)
        				.addComponent(txtTelefone, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(23)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblNewLabel)
        				.addComponent(txtEndereco, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(txtEmail, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel_1))
        			.addGap(36)
        			.addComponent(rbPRF)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(rbAluno)
        			.addGap(34)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblCPF)
        				.addComponent(txtCPF, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblMatricula)
        				.addComponent(txtMatricula, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(45)
        			.addComponent(btnSalvar)
        			.addGap(182))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPJActionPerformed

    private void rbPFItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPFItemStateChanged
        verificarTipoPessoa();
    }//GEN-LAST:event_rbPFItemStateChanged

    private void rbPJItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbPJItemStateChanged
        verificarTipoPessoa();
    }//GEN-LAST:event_rbPJItemStateChanged

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       
        String nome = txtNome.getText();
        String fone = txtTelefone.getText();
        String endereco = txtEndereco.getText();
        String email = txtEmail.getText();
        
        
		if( rbPRF.isSelected() ){
            Aluno clienteAlu = new  Aluno();
            clienteAlu.nome = nome;
            clienteAlu.telefone = fone;
            clienteAlu.endereco = endereco;
             clienteAlu.email = email;
            clienteAlu.matricula = txtMatricula.getText();
            
        }else if( rbAluno.isSelected() ){
            Professor clientePRF = new Professor();
            clientePRF.nome = nome;
            clientePRF.telefone = fone;
            clientePRF.endereco = endereco;
            clientePRF.email = email;
            clientePRF.cpf = txtCPF.getText();
        }else{
            Cliente cliente = new Cliente();
            cliente.nome = nome;
            cliente.telefone = fone;
            cliente.endereco = endereco;
            cliente.email = email;
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void verificarTipoPessoa(){
        if( rbPRF.isSelected() ){
            
            lblCPF.setEnabled( true );
            txtCPF.setEnabled( true );
            lblCPF.setVisible( true );
            txtCPF.setVisible( true );
            
            lblMatricula.setEnabled( false );
            txtMatricula.setEnabled( false );
            lblMatricula.setVisible( false );
            txtMatricula.setVisible( false );
            
        }else if( rbAluno.isSelected() ){
            
            lblCPF.setEnabled( false );
            txtCPF.setEnabled( false );
            lblCPF.setVisible( false );
            txtCPF.setVisible( false );
            
            lblMatricula.setEnabled( true );
            txtMatricula.setEnabled( true );
            lblMatricula.setVisible( true );
            txtMatricula.setVisible( true );
        }else{
            
            lblCPF.setEnabled( false );
            txtCPF.setEnabled( false );
            lblCPF.setVisible( false );
            txtCPF.setVisible( false );
            
            lblMatricula.setEnabled( false );
            txtMatricula.setEnabled( false );
            lblMatricula.setVisible( false );
            txtMatricula.setVisible( false );
        }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.ButtonGroup buttonGroupTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JRadioButton rbPRF;
    private javax.swing.JRadioButton rbAluno;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    private JTextField txtMatricula;
    private JTextField txtEndereco;
    private JTextField txtEmail;
}
